# Generated by Django 5.0.3 on 2024-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0002_alter_informacoes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoes',
            name='relatorio',
            field=models.TextField(default='Este é um relatório padrão'),
        ),
    ]
