# Generated by Django 5.0.3 on 2024-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0003_informacoes_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoes',
            name='relatorio',
            field=models.TextField(default='Relatório padrão'),
        ),
    ]
